// =====================================================================
//  THE ZOMBIES 2.0 — game data
// =====================================================================
'use strict';

// ---------------------------------------------------------------- ITEMS
// type: weapon | throw | ammo | food | med | mat | part | tool | wear | quest
// wear slot: head | body | back
TZ.ITEMS = {
  // ---- melee ----
  knife:     { name: 'Нож', type: 'weapon', w: 0.4, desc: 'Быстрый и тихий. Вызывает кровотечение.' },
  machete:   { name: 'Мачете', type: 'weapon', w: 0.9, desc: 'Широкий взмах, хорошо режет толпу.' },
  crowbar:   { name: 'Лом', type: 'weapon', w: 1.6, desc: 'Тяжёлый удар. Вскрывает запертые ящики быстрее.' },
  bat:       { name: 'Бита с гвоздями', type: 'weapon', w: 1.4, desc: 'Сильно отбрасывает врагов.' },
  axe:       { name: 'Топор', type: 'weapon', w: 1.8, desc: 'Рубит деревья и головы. Добывает дерево.' },
  pickaxe:   { name: 'Кирка', type: 'weapon', w: 2.2, desc: 'Добывает камень и металл.' },
  sledge:    { name: 'Кувалда', type: 'weapon', w: 4.0, desc: 'Медленная, но сносит даже громил. Быстро ломает обломки машин.' },
  katana:    { name: 'Катана', type: 'weapon', w: 1.2, desc: 'Редкий клинок. Огромный урон и скорость.' },
  chainsaw:  { name: 'Бензопила', type: 'weapon', w: 5.0, desc: 'Рвёт всё перед собой. Тратит топливо. Мгновенно валит деревья.' },
  wrench:    { name: 'Гаечный ключ', type: 'weapon', w: 0.8, desc: 'Нужен для ремонта машин. Можно и ударить.' },
  hammer:    { name: 'Молоток', type: 'weapon', w: 0.9, desc: 'Чинит ваши постройки ударом (тратит материал). У своей стены нажмите E — улучшить: дерево → камень → сталь.' },
  spear:     { name: 'Копьё', type: 'weapon', w: 1.6, desc: 'Длинный выпад: бьёт врагов на расстоянии, пока они не дотянулись до вас.' },
  fireaxe:   { name: 'Пожарный топор', type: 'weapon', w: 2.6, desc: 'Тяжёлый красный топор. Рубит деревья вдвое быстрее и разбирает обломки.' },
  torch_h:   { name: 'Факел', type: 'weapon', w: 0.6, desc: 'Освещает всё вокруг и поджигает зомби при ударе. Горит, пока в руке.' },
  shovel:    { name: 'Лопата', type: 'weapon', w: 1.8, desc: 'Можно ударить. Главное — выкапывать тайники, найденные металлоискателем.' },
  detector:  { name: 'Металлоискатель', type: 'weapon', w: 1.4, desc: 'Возьмите в руки: пищит чаще рядом с закопанным тайником. Копайте лопатой.' },
  walkie:    { name: 'Рация', type: 'tool', w: 0.4, desc: 'Голосовой чат слышен на любом расстоянии всем, у кого тоже есть рация. Сообщения /r в чате.' },
  rod:       { name: 'Удочка', type: 'weapon', w: 0.8, desc: 'Подойдите к воде и нажмите E, чтобы рыбачить.' },
  // ---- guns ----
  pistol:    { name: 'Пистолет ПМ', type: 'weapon', w: 0.9, desc: 'Надёжный пистолет. Патроны 9мм.' },
  revolver:  { name: 'Револьвер', type: 'weapon', w: 1.2, desc: 'Мощный, но медленный. Патроны .357.' },
  smg:       { name: 'ПП «Кедр»', type: 'weapon', w: 1.8, desc: 'Пистолет-пулемёт. Очень быстрый огонь 9мм.' },
  sawnoff:   { name: 'Обрез', type: 'weapon', w: 2.0, desc: 'Два ствола, страшный урон в упор. 12 калибр.' },
  shotgun:   { name: 'Дробовик', type: 'weapon', w: 3.2, desc: 'Помповый. Разрывает толпу. 12 калибр.' },
  ak:        { name: 'Автомат АК', type: 'weapon', w: 3.6, desc: 'Автоматический огонь. Патроны 7.62.' },
  rifle:     { name: 'Охотничья винтовка', type: 'weapon', w: 3.4, desc: 'Пробивает нескольких зомби насквозь. 7.62.' },
  svd:       { name: 'Снайперская СВД', type: 'weapon', w: 4.3, desc: 'Военная снайперка. Пробивает целую колонну. 7.62.' },
  crossbow:  { name: 'Арбалет', type: 'weapon', w: 2.4, desc: 'Бесшумный. Болты можно подбирать.' },
  flamer:    { name: 'Огнемёт', type: 'weapon', w: 6.0, desc: 'Поток огня. Заправляется канистрами топлива.' },
  bow:       { name: 'Лук', type: 'weapon', w: 1.0, desc: 'Тихий и лёгкий. Стрелы можно подобрать после выстрела.' },
  nailgun:   { name: 'Гвоздемёт', type: 'weapon', w: 2.2, desc: 'Строительный инструмент как оружие: тихая очередь гвоздями.' },
  pkm:       { name: 'Пулемёт ПКМ', type: 'weapon', w: 8.0, desc: 'Лента на 100 патронов 7.62. Очень тяжёлый — с ним вы ходите медленнее.' },
  glauncher: { name: 'Гранатомёт', type: 'weapon', w: 4.5, desc: 'Выстрел взрывается при попадании. Снаряды — 40-мм гранаты.' },
  flaregun:  { name: 'Ракетница', type: 'weapon', w: 0.8, desc: 'Сигнальная ракета освещает округу и поджигает. Раз в день вызывает сброс груза туда, куда упала.' },
  // ---- throwables ----
  molotov:   { name: 'Коктейль Молотова', type: 'throw', w: 0.6, stack: 10, desc: 'Поджигает область.' },
  grenade:   { name: 'Граната', type: 'throw', w: 0.5, stack: 10, desc: 'Взрыв через 2 секунды. Разносит толпы.' },
  pipebomb:  { name: 'Самодельная бомба', type: 'throw', w: 0.7, stack: 10, desc: 'Пищит и приманивает зомби, затем взрывается.' },
  decoy:     { name: 'Шумовая приманка', type: 'throw', w: 0.4, stack: 10, desc: '15 секунд пищит и мигает — зомби идут на звук, а не к вам. Не взрывается.' },
  // ---- ammo ----
  ammo9:     { name: 'Патроны 9мм', type: 'ammo', w: 0.01, stack: 999, desc: 'Для ПМ, ПП и турелей.' },
  ammo357:   { name: 'Патроны .357', type: 'ammo', w: 0.02, stack: 999, desc: 'Для револьвера.' },
  ammo12:    { name: 'Патроны 12 кал.', type: 'ammo', w: 0.04, stack: 999, desc: 'Для дробовика и обреза.' },
  ammo762:   { name: 'Патроны 7.62', type: 'ammo', w: 0.02, stack: 999, desc: 'Для АК, винтовок и тяжёлой турели.' },
  bolt:      { name: 'Арбалетный болт', type: 'ammo', w: 0.05, stack: 99, desc: 'Для арбалета.' },
  arrow:     { name: 'Стрела', type: 'ammo', w: 0.03, stack: 99, desc: 'Для лука.' },
  nails:     { name: 'Гвозди', type: 'ammo', w: 0.005, stack: 999, desc: 'Для гвоздемёта.' },
  gl_shell:  { name: 'Граната 40 мм', type: 'ammo', w: 0.25, stack: 30, desc: 'Для гранатомёта.' },
  flare:     { name: 'Сигнальная ракета', type: 'ammo', w: 0.1, stack: 20, desc: 'Для ракетницы.' },
  // ---- food / drink ----
  canned:    { name: 'Тушёнка', type: 'food', w: 0.4, stack: 20, food: 35, desc: '+35 сытости.' },
  beans:     { name: 'Фасоль', type: 'food', w: 0.4, stack: 20, food: 28, water: 4, desc: '+28 сытости.' },
  chips:     { name: 'Чипсы', type: 'food', w: 0.1, stack: 20, food: 12, water: -4, desc: '+12 сытости, хочется пить.' },
  choco:     { name: 'Шоколад', type: 'food', w: 0.1, stack: 20, food: 15, stamina: 30, desc: '+15 сытости, +30 сил.' },
  mre:       { name: 'Сухпаёк', type: 'food', w: 0.6, stack: 10, food: 60, water: 20, desc: 'Армейский рацион. +60 сытости, +20 воды.' },
  apple:     { name: 'Яблоко', type: 'food', w: 0.15, stack: 30, food: 10, water: 6, desc: '+10 сытости.' },
  berries:   { name: 'Ягоды', type: 'food', w: 0.1, stack: 30, food: 8, water: 4, desc: 'С лесных кустов.' },
  veggie:    { name: 'Овощи', type: 'food', w: 0.3, stack: 30, food: 18, water: 8, desc: 'С грядки.' },
  raw_meat:  { name: 'Сырое мясо', type: 'food', w: 0.5, stack: 20, food: 10, sick: 0.4, desc: 'Лучше пожарить на костре. Можно отравиться.' },
  steak:     { name: 'Жареное мясо', type: 'food', w: 0.4, stack: 20, food: 45, desc: '+45 сытости.' },
  fish:      { name: 'Сырая рыба', type: 'food', w: 0.4, stack: 20, food: 8, sick: 0.3, desc: 'Пожарьте на костре.' },
  fish_cooked: { name: 'Жареная рыба', type: 'food', w: 0.3, stack: 20, food: 34, water: 4, desc: '+34 сытости.' },
  junk_boot: { name: 'Старый сапог', type: 'mat', w: 0.6, stack: 20, desc: 'Улов неудачника. Можно разобрать на кожу на верстаке.' },
  water:     { name: 'Бутылка воды', type: 'food', w: 0.5, stack: 20, water: 40, desc: '+40 к жажде.' },
  dirty_water: { name: 'Грязная вода', type: 'food', w: 0.5, stack: 20, water: 25, sick: 0.3, desc: 'Можно прокипятить на костре.' },
  soda:      { name: 'Газировка', type: 'food', w: 0.35, stack: 20, water: 25, stamina: 20, desc: '+25 воды.' },
  energy:    { name: 'Энергетик', type: 'food', w: 0.3, stack: 10, water: 15, stamina: 100, desc: 'Полностью восстанавливает силы.' },
  coffee:    { name: 'Кофе', type: 'food', w: 0.2, stack: 10, water: 10, stamina: 60, warm: 20, desc: 'Бодрит и согревает.' },
  vodka:     { name: 'Водка', type: 'food', w: 0.6, stack: 10, water: -10, warm: 60, desc: 'Сильно согревает. Немного шатает.' },
  // ---- medicine ----
  bandage:   { name: 'Бинт', type: 'med', w: 0.1, stack: 20, heal: 15, stopBleed: true, desc: '+15 здоровья, останавливает кровотечение.' },
  medkit:    { name: 'Аптечка', type: 'med', w: 0.8, stack: 10, heal: 60, stopBleed: true, desc: '+60 здоровья.' },
  antibio:   { name: 'Антибиотики', type: 'med', w: 0.1, stack: 10, heal: 5, cure: true, desc: 'Лечит заражение и отравление.' },
  painkill:  { name: 'Обезболивающее', type: 'med', w: 0.1, stack: 10, heal: 10, buff: 'tough', desc: '30 секунд вы получаете на 40% меньше урона.' },
  adrenaline:{ name: 'Адреналин', type: 'med', w: 0.1, stack: 5, heal: 20, buff: 'fast', desc: '20 секунд вы бегаете быстрее и не устаёте.' },
  // ---- materials ----
  wood:      { name: 'Дерево', type: 'mat', w: 0.2, stack: 999, desc: 'Основной строительный материал.' },
  stone:     { name: 'Камень', type: 'mat', w: 0.3, stack: 999, desc: 'Для каменных стен и костров.' },
  metal:     { name: 'Металлолом', type: 'mat', w: 0.25, stack: 999, desc: 'Для прочных стен, оружия и машин.' },
  cloth:     { name: 'Ткань', type: 'mat', w: 0.1, stack: 999, desc: 'Бинты, одежда, факелы.' },
  rope:      { name: 'Верёвка', type: 'mat', w: 0.15, stack: 999, desc: 'Для рюкзаков, ловушек, арбалета.' },
  parts:     { name: 'Детали', type: 'mat', w: 0.15, stack: 999, desc: 'Механизмы, пружины, винты.' },
  electro:   { name: 'Электроника', type: 'mat', w: 0.1, stack: 999, desc: 'Платы и провода. Для турелей, прожекторов, рации.' },
  gunpowder: { name: 'Порох', type: 'mat', w: 0.05, stack: 999, desc: 'Для патронов и взрывчатки.' },
  leather:   { name: 'Кожа', type: 'mat', w: 0.3, stack: 999, desc: 'С оленей и медведей.' },
  fur:       { name: 'Мех', type: 'mat', w: 0.3, stack: 999, desc: 'С волков и медведей. Для тёплой одежды.' },
  fuel:      { name: 'Канистра топлива', type: 'mat', w: 2.0, stack: 20, desc: 'Заправляет машины, бензопилу и огнемёт.' },
  pipe:      { name: 'Трубы', type: 'mat', w: 0.5, stack: 999, desc: 'Стальные трубы. Из них собирают раму самодельного вертолёта или самолёта.' },
  brick:     { name: 'Кирпич', type: 'mat', w: 0.4, stack: 999, desc: 'Обожжённый на костре камень. Для кирпичных стен и домов.' },
  concrete:  { name: 'Цемент', type: 'mat', w: 0.6, stack: 999, desc: 'Для бетонных стен.' },
  // ---- vehicle parts ----
  wheel:     { name: 'Колесо', type: 'part', w: 4.0, stack: 8, desc: 'Запасное колесо для машины.' },
  battery:   { name: 'Аккумулятор', type: 'part', w: 3.0, stack: 4, desc: 'Без него машина не заведётся.' },
  engine:    { name: 'Двигатель', type: 'part', w: 8.0, stack: 2, desc: 'Нужен для сборки багги.' },
  repairkit: { name: 'Ремкомплект', type: 'part', w: 1.2, stack: 10, desc: 'Чинит машину на 35%. Нужен гаечный ключ.' },
  // ---- tools ----
  flashlight:{ name: 'Фонарик', type: 'tool', w: 0.3, stack: 1, desc: 'Клавиша L. Светит туда, куда вы смотрите.' },
  binoc:     { name: 'Бинокль', type: 'tool', w: 0.5, stack: 1, desc: 'Пока лежит в сумке, камера видит дальше.' },
  leash:     { name: 'Ошейник', type: 'tool', w: 0.2, stack: 3, desc: 'Используйте вместе с мясом, чтобы приручить бездомную собаку (E рядом с ней).' },
  // ---- wearables ----
  cap:       { name: 'Кепка', type: 'wear', slot: 'head', w: 0.1, stack: 1, armor: 0, warm: 2, desc: 'Ваша старая кепка.' },
  beanie:    { name: 'Вязаная шапка', type: 'wear', slot: 'head', w: 0.1, stack: 1, armor: 0, warm: 10, desc: 'Немного греет.' },
  ushanka:   { name: 'Шапка-ушанка', type: 'wear', slot: 'head', w: 0.3, stack: 1, armor: 2, warm: 25, desc: 'Спасает от мороза.' },
  helmet:    { name: 'Военная каска', type: 'wear', slot: 'head', w: 1.2, stack: 1, armor: 15, warm: 0, desc: '-15% урона.' },
  nvg:       { name: 'Прибор ночного видения', type: 'wear', slot: 'head', w: 0.9, stack: 1, armor: 2, warm: 0, nv: true, desc: 'Ночью видно почти как днём (зелёная картинка).' },
  gasmask:   { name: 'Противогаз', type: 'wear', slot: 'head', w: 0.8, stack: 1, armor: 3, warm: 0, toxic: true, desc: 'Защищает от болотного газа и кислоты плевунов.' },
  jacket:    { name: 'Куртка', type: 'wear', slot: 'body', w: 1.0, stack: 1, armor: 5, warm: 15, desc: 'Обычная куртка.' },
  parka:     { name: 'Тёплая парка', type: 'wear', slot: 'body', w: 1.8, stack: 1, armor: 6, warm: 45, desc: 'Для заснеженной тайги.' },
  vest:      { name: 'Бронежилет', type: 'wear', slot: 'body', w: 4.0, stack: 1, armor: 35, warm: 5, desc: '-35% урона.' },
  bp_small:  { name: 'Рюкзак', type: 'wear', slot: 'back', w: 0.8, stack: 1, carry: 15, desc: '+15 к переносимому весу.' },
  bp_big:    { name: 'Туристический рюкзак', type: 'wear', slot: 'back', w: 1.4, stack: 1, carry: 30, desc: '+30 к весу.' },
  bp_mil:    { name: 'Военный рюкзак', type: 'wear', slot: 'back', w: 1.8, stack: 1, carry: 45, desc: '+45 к весу.' },
  // ---- quest ----
  radiopart: { name: 'Деталь рации', type: 'quest', w: 0.5, stack: 3, desc: 'Соберите 3 детали, чтобы построить радиостанцию и вызвать эвакуацию.' },
};
for (const k in TZ.ITEMS) { const it = TZ.ITEMS[k]; it.id = k; if (!it.stack) it.stack = it.type === 'weapon' ? 1 : 99; }
TZ.ITEM_CATS = [['all', 'Всё'], ['weapon', 'Оружие'], ['ammo', 'Патроны'], ['food', 'Еда'], ['med', 'Аптека'], ['mat', 'Материалы'], ['wear', 'Одежда']];
TZ.itemCat = (id) => { const t = TZ.ITEMS[id].type; return t === 'throw' ? 'weapon' : t === 'part' || t === 'tool' || t === 'quest' ? 'mat' : t; };

// ---------------------------------------------------------------- WEAPONS
// hold: one | two | melee  (voxel arm pose)
TZ.WEAPONS = {
  fists:   { melee: 1, dmg: 8, range: 1.05, arc: 1.2, cd: 0.38, stam: 4, knock: 0.25, sound: 'swing', hold: 'free' },
  knife:   { melee: 1, dmg: 22, range: 1.15, arc: 1.25, cd: 0.3, stam: 4, knock: 0.25, sound: 'swing', bleed: 1, hold: 'melee' },
  machete: { melee: 1, dmg: 30, range: 1.35, arc: 1.9, cd: 0.42, stam: 7, knock: 0.4, sound: 'swing', bleed: 1, hold: 'melee' },
  crowbar: { melee: 1, dmg: 32, range: 1.35, arc: 1.4, cd: 0.5, stam: 8, knock: 0.6, sound: 'swing_heavy', hold: 'melee', pry: 1 },
  bat:     { melee: 1, dmg: 34, range: 1.45, arc: 1.7, cd: 0.55, stam: 9, knock: 0.9, sound: 'swing_heavy', hold: 'melee' },
  axe:     { melee: 1, dmg: 30, range: 1.38, arc: 1.4, cd: 0.55, stam: 9, knock: 0.5, chop: 1, sound: 'swing_heavy', hold: 'melee' },
  pickaxe: { melee: 1, dmg: 26, range: 1.38, arc: 1.2, cd: 0.62, stam: 10, knock: 0.45, mine: 1, sound: 'swing_heavy', hold: 'melee' },
  sledge:  { melee: 1, dmg: 75, range: 1.55, arc: 1.8, cd: 1.1, stam: 18, knock: 1.6, mine: 1, wreck: 1, sound: 'swing_heavy', hold: 'melee' },
  katana:  { melee: 1, dmg: 48, range: 1.5, arc: 1.8, cd: 0.36, stam: 7, knock: 0.4, bleed: 1, sound: 'swing', hold: 'melee' },
  chainsaw:{ melee: 1, dmg: 14, range: 1.3, arc: 1.0, cd: 0.07, stam: 0, knock: 0.15, chop: 4, bleed: 1, fuelUse: 0.012, sound: 'chainsaw', hold: 'two', auto: 1 },
  wrench:  { melee: 1, dmg: 16, range: 1.15, arc: 1.2, cd: 0.42, stam: 5, knock: 0.35, sound: 'swing', hold: 'melee', wreck: 1 },
  hammer:  { melee: 1, dmg: 14, range: 1.15, arc: 1.2, cd: 0.4, stam: 4, knock: 0.35, sound: 'swing', hold: 'melee', repair: 1 },
  spear:   { melee: 1, dmg: 36, range: 1.95, arc: 0.55, cd: 0.5, stam: 7, knock: 0.7, sound: 'swing', hold: 'melee', bleed: 1 },
  fireaxe: { melee: 1, dmg: 46, range: 1.4, arc: 1.5, cd: 0.7, stam: 12, knock: 0.8, chop: 2, wreck: 1, sound: 'swing_heavy', hold: 'melee' },
  torch_h: { melee: 1, dmg: 12, range: 1.15, arc: 1.3, cd: 0.42, stam: 4, knock: 0.3, sound: 'swing', hold: 'melee', ignite: 1, light: 6 },
  shovel:  { melee: 1, dmg: 24, range: 1.3, arc: 1.3, cd: 0.6, stam: 8, knock: 0.6, sound: 'swing_heavy', hold: 'melee', dig: 1 },
  detector:{ melee: 1, dmg: 4, range: 1.1, arc: 1.0, cd: 0.6, stam: 3, knock: 0.1, sound: 'swing', hold: 'one', detect: 1 },
  rod:     { melee: 1, dmg: 3, range: 1.2, arc: 1.0, cd: 0.5, stam: 2, knock: 0.1, sound: 'swing', hold: 'melee', fish: 1 },
  flaregun:{ ammo: 'flare', mag: 1, dmg: 25, cd: 0.6, spread: 0.02, reload: 1.3, pellets: 1, range: 16, noise: 10, speed: 13, recoil: 3, knock: 0.3, sound: 'pistol', hold: 'one', flare: 1 },
  pistol:  { ammo: 'ammo9', mag: 12, dmg: 28, cd: 0.2, spread: 0.035, reload: 1.1, pellets: 1, range: 15, noise: 14, speed: 30, recoil: 2, knock: 0.25, sound: 'pistol', hold: 'one' },
  revolver:{ ammo: 'ammo357', mag: 6, dmg: 70, cd: 0.45, spread: 0.02, reload: 2.0, pellets: 1, range: 17, noise: 18, speed: 34, recoil: 5, knock: 0.7, pierce: 2, sound: 'revolver', hold: 'one' },
  smg:     { ammo: 'ammo9', mag: 30, dmg: 20, cd: 0.065, spread: 0.1, reload: 1.6, pellets: 1, range: 12, noise: 16, speed: 30, recoil: 1.4, knock: 0.15, auto: 1, sound: 'smg', hold: 'two' },
  sawnoff: { ammo: 'ammo12', mag: 2, dmg: 18, cd: 0.3, spread: 0.34, reload: 1.8, pellets: 10, range: 6, noise: 22, speed: 24, recoil: 8, knock: 0.7, sound: 'shotgun', hold: 'two' },
  shotgun: { ammo: 'ammo12', mag: 6, dmg: 15, cd: 0.78, spread: 0.24, reload: 2.1, pellets: 8, range: 8.5, noise: 20, speed: 26, recoil: 6, knock: 0.5, sound: 'shotgun', hold: 'two' },
  ak:      { ammo: 'ammo762', mag: 30, dmg: 30, cd: 0.105, spread: 0.075, reload: 2.0, pellets: 1, range: 17, noise: 22, speed: 34, recoil: 2.5, knock: 0.3, auto: 1, sound: 'rifle', hold: 'two' },
  rifle:   { ammo: 'ammo762', mag: 5, dmg: 110, cd: 0.95, spread: 0.004, reload: 2.4, pellets: 1, range: 24, noise: 24, speed: 44, recoil: 7, knock: 0.9, pierce: 4, sound: 'sniper', hold: 'two' },
  svd:     { ammo: 'ammo762', mag: 10, dmg: 140, cd: 0.6, spread: 0.003, reload: 2.6, pellets: 1, range: 30, noise: 26, speed: 50, recoil: 6, knock: 1.0, pierce: 7, sound: 'sniper', hold: 'two', zoom: 1 },
  crossbow:{ ammo: 'bolt', mag: 1, dmg: 95, cd: 0.4, spread: 0.01, reload: 1.3, pellets: 1, range: 18, noise: 2, speed: 26, recoil: 1, knock: 0.6, pierce: 2, sound: 'crossbow', hold: 'two', bolt: 1 },
  bow:     { ammo: 'arrow', mag: 1, dmg: 70, cd: 0.3, spread: 0.015, reload: 0.55, pellets: 1, range: 17, noise: 1, speed: 24, recoil: 0.5, knock: 0.45, pierce: 1, sound: 'crossbow', hold: 'two', bolt: 1 },
  nailgun: { ammo: 'nails', mag: 40, dmg: 17, cd: 0.11, spread: 0.07, reload: 1.8, pellets: 1, range: 9, noise: 5, speed: 26, recoil: 0.8, knock: 0.15, auto: 1, sound: 'nailgun', hold: 'two' },
  pkm:     { ammo: 'ammo762', mag: 100, dmg: 34, cd: 0.085, spread: 0.1, reload: 4.4, pellets: 1, range: 20, noise: 26, speed: 36, recoil: 2.2, knock: 0.35, pierce: 2, auto: 1, sound: 'rifle', hold: 'two', heavy: 0.82 },
  glauncher:{ ammo: 'gl_shell', mag: 1, dmg: 20, cd: 0.6, spread: 0.02, reload: 1.6, pellets: 1, range: 16, noise: 20, speed: 15, recoil: 6, knock: 0.6, sound: 'gl', hold: 'two', gl: { r: 2.7, dmg: 100 } },
  flamer:  { ammo: 'fuel', mag: 100, pack: 100, dmg: 6, cd: 0.05, spread: 0.18, reload: 2.2, pellets: 1, range: 5.5, noise: 6, speed: 9, recoil: 0.3, knock: 0.05, auto: 1, flame: 1, sound: 'flamer', hold: 'two' },
  molotov: { throw: 1, cd: 0.8, range: 8 },
  grenade: { throw: 1, cd: 0.8, range: 9 },
  pipebomb:{ throw: 1, cd: 0.8, range: 9 },
  decoy:   { throw: 1, cd: 0.8, range: 11 },
};

// ---------------------------------------------------------------- BUILDINGS
TZ.BUILD = {
  wall_wood:  { name: 'Частокол', cat: 'wall', cost: { wood: 4 }, hp: 160, solid: 1, kind: 'wall', desc: 'Деревянная стена. Дёшево и быстро.' },
  wall_stone: { name: 'Каменная стена', cat: 'wall', cost: { stone: 6, wood: 1 }, hp: 420, solid: 1, kind: 'wall', desc: 'В 2.5 раза прочнее дерева.' },
  wall_metal: { name: 'Стальная стена', cat: 'wall', cost: { metal: 6, wood: 2 }, hp: 800, solid: 1, kind: 'wall', desc: 'Почти неприступна.' },
  wall_concrete: { name: 'Бетонная стена', cat: 'wall', cost: { concrete: 6, metal: 2 }, hp: 1400, solid: 1, kind: 'wall', needs: 'workbench', desc: 'Самая прочная стена.' },
  wall_brick: { name: 'Кирпичная стена', cat: 'house', cost: { brick: 4 }, hp: 650, solid: 1, kind: 'wall', house: 1, desc: 'Стена дома. Соединяется с соседними стенами и держит крышу.' },
  wall_brick_win: { name: 'Стена с окном', cat: 'house', cost: { brick: 3, wood: 1 }, hp: 480, solid: 1, kind: 'wall', house: 1, win: 1, desc: 'Кирпичная стена с окном.' },
  door_wood:  { name: 'Дверь', cat: 'house', cost: { wood: 6, metal: 1 }, hp: 320, solid: 1, gate: 'door', kind: 'wall', house: 1, desc: 'Открывается перед игроками и союзниками, зомби не пускает.' },
  door_code:  { name: 'Дверь с кодом', cat: 'house', cost: { metal: 8, electro: 2, brick: 2 }, hp: 900, solid: 1, gate: 'door_code', kind: 'wall', house: 1, needs: 'workbench', desc: 'Стальная дверь с кодовым замком. Чужие не видят, что внутри.' },
  roof_wood:  { name: 'Деревянная крыша', cat: 'house', cost: { wood: 3 }, hp: 100, kind: 'roof', roof: 5, desc: 'Ставится над клеткой рядом со стеной. Снаружи закрывает дом, внутри исчезает.' },
  roof_concrete: { name: 'Бетонная крыша', cat: 'house', cost: { concrete: 2, metal: 1 }, hp: 300, kind: 'roof', roof: 6, desc: 'Плоская бетонная крыша.' },
  sandbags:   { name: 'Мешки с песком', cat: 'wall', cost: { cloth: 3, stone: 3 }, hp: 300, solid: 1, kind: 'wall', low: 1, desc: 'Низкое укрытие.' },
  gate_wood:  { name: 'Деревянные ворота', cat: 'gate', cost: { wood: 8, metal: 1 }, hp: 260, solid: 1, gate: 'wood', kind: 'wall', desc: 'Открываются перед игроками и союзниками, но не перед зомби.' },
  gate_metal: { name: 'Стальные ворота', cat: 'gate', cost: { metal: 10, parts: 2 }, hp: 700, solid: 1, gate: 'metal', kind: 'wall', desc: 'Прочные ворота на петлях.' },
  gate_code:  { name: 'Кодовые ворота', cat: 'gate', cost: { metal: 12, parts: 4, electro: 3 }, hp: 900, solid: 1, gate: 'code', kind: 'wall', needs: 'workbench', desc: 'Открываются только тем, кто знает код. Чужие игроки не видят, что внутри базы.' },
  spikes:     { name: 'Шипы', cat: 'trap', cost: { wood: 3, metal: 1 }, hp: 100, kind: 'trap', desc: 'Ранят и замедляют зомби.' },
  barbed:     { name: 'Колючая проволока', cat: 'trap', cost: { metal: 3, rope: 1 }, hp: 140, kind: 'trap', desc: 'Сильно замедляет и режет зомби.' },
  mine:       { name: 'Мина', cat: 'trap', cost: { metal: 2, gunpowder: 4, parts: 1 }, hp: 40, kind: 'trap', needs: 'workbench', desc: 'Взрывается, когда на неё наступает зомби.' },
  beartrap:   { name: 'Капкан', cat: 'trap', cost: { metal: 4, parts: 1 }, hp: 90, kind: 'trap', desc: 'Захлопывается на зомби: держит 4 секунды и сильно ранит. Перезаряжается сам.' },
  barrel_bomb:{ name: 'Взрывная бочка', cat: 'trap', cost: { metal: 3, fuel: 1 }, hp: 30, solid: 1, kind: 'trap', desc: 'Взрывается от выстрела.' },
  turret:     { name: 'Турель 9мм', cat: 'defense', cost: { metal: 14, parts: 8, electro: 2 }, hp: 300, solid: 1, kind: 'turret', needs: 'workbench', ammo: 'ammo9', desc: 'Стреляет по зомби. Заряжается патронами 9мм [E].' },
  turret_heavy:{ name: 'Пулемётная турель', cat: 'defense', cost: { metal: 25, parts: 14, electro: 6 }, hp: 600, solid: 1, kind: 'turret', needs: 'workbench', ammo: 'ammo762', desc: 'Мощная турель на 7.62.' },
  torch:      { name: 'Факел', cat: 'light', cost: { wood: 1, cloth: 1 }, hp: 40, kind: 'light', light: 5.5, desc: 'Освещает территорию.' },
  campfire:   { name: 'Костёр', cat: 'light', cost: { wood: 5, stone: 3 }, hp: 120, solid: 1, kind: 'light', light: 8, station: 'fire', desc: 'Свет и тепло. На нём жарят мясо и кипятят воду.' },
  floodlight: { name: 'Прожектор', cat: 'light', cost: { metal: 5, parts: 3, electro: 2 }, hp: 150, solid: 1, kind: 'light', light: 11, needs: 'workbench', desc: 'Мощный свет.' },
  workbench:  { name: 'Верстак', cat: 'station', cost: { wood: 8, metal: 4 }, hp: 200, solid: 1, kind: 'station', station: 'bench', desc: 'Продвинутый крафт: оружие, патроны, взрывчатка.' },
  garage:     { name: 'Гаражный пост', cat: 'station', cost: { metal: 20, parts: 10, wood: 6 }, hp: 400, solid: 1, kind: 'station', station: 'garage', needs: 'workbench', desc: 'Сборка машин и ремонт без ремкомплекта.' },
  bed:        { name: 'Кровать', cat: 'station', cost: { wood: 6, cloth: 4 }, hp: 120, solid: 1, kind: 'bed', desc: 'Точка возрождения и сохранение.' },
  sleepbag:   { name: 'Спальник', cat: 'station', cost: { cloth: 6, rope: 1 }, hp: 60, kind: 'bed', desc: 'Дешёвая точка возрождения — удобно для вылазок далеко от базы.' },
  chest:      { name: 'Ящик', cat: 'station', cost: { wood: 6, metal: 1 }, hp: 150, solid: 1, kind: 'storage', desc: 'Хранилище на 40 ячеек. Материалы из ящиков рядом идут на стройку.' },
  garden:     { name: 'Грядка', cat: 'farm', cost: { wood: 5, cloth: 1 }, hp: 60, kind: 'farm', desc: 'Овощи каждые ~1.5 дня.' },
  collector:  { name: 'Сборщик воды', cat: 'farm', cost: { wood: 4, cloth: 3, metal: 2 }, hp: 100, solid: 1, kind: 'farm', desc: 'Собирает чистую воду.' },
  floor_wood: { name: 'Деревянный пол', cat: 'deco', cost: { wood: 2 }, hp: 50, kind: 'floor', desc: 'Красивый пол для базы.' },
  floor_stone:{ name: 'Каменный пол', cat: 'deco', cost: { stone: 2 }, hp: 80, kind: 'floor', desc: 'Плитка из камня.' },
  radio:      { name: 'Радиостанция', cat: 'station', cost: { radiopart: 3, metal: 10, electro: 6 }, hp: 400, solid: 1, kind: 'radio', needs: 'workbench', desc: 'Вызывает эвакуацию.' },
};
for (const k in TZ.BUILD) TZ.BUILD[k].id = k;
TZ.isCode = t => t === 'gate_code' || t === 'door_code';
TZ.BUILD_CATS = [['house', 'Дом'], ['wall', 'Стены'], ['gate', 'Ворота'], ['trap', 'Ловушки'], ['defense', 'Оборона'], ['light', 'Свет'], ['station', 'База'], ['farm', 'Ферма'], ['deco', 'Декор']];

// ---------------------------------------------------------------- RECIPES
// st: null | bench | fire | garage
TZ.RECIPES = [
  { out: 'bandage', n: 2, cost: { cloth: 2 } },
  { out: 'rope', n: 1, cost: { cloth: 3 } },
  { out: 'medkit', n: 1, cost: { bandage: 2, antibio: 1, cloth: 2 }, st: 'bench' },
  { out: 'painkill', n: 2, cost: { antibio: 1, parts: 1 }, st: 'bench' },
  { out: 'steak', n: 1, cost: { raw_meat: 1 }, st: 'fire' },
  { out: 'water', n: 1, cost: { dirty_water: 1 }, st: 'fire' },
  { out: 'coffee', n: 1, cost: { water: 1, choco: 1 }, st: 'fire' },
  { out: 'gunpowder', n: 3, cost: { stone: 2, fuel: 1 }, st: 'bench' },
  { out: 'concrete', n: 4, cost: { stone: 6, water: 1 }, st: 'bench' },
  { out: 'molotov', n: 1, cost: { fuel: 1, cloth: 1 } },
  { out: 'grenade', n: 2, cost: { metal: 2, gunpowder: 3, parts: 1 }, st: 'bench' },
  { out: 'pipebomb', n: 1, cost: { metal: 2, gunpowder: 2, electro: 1 }, st: 'bench' },
  { out: 'ammo9', n: 15, cost: { metal: 2, gunpowder: 1 }, st: 'bench' },
  { out: 'ammo357', n: 8, cost: { metal: 2, gunpowder: 1 }, st: 'bench' },
  { out: 'ammo12', n: 8, cost: { metal: 3, gunpowder: 2 }, st: 'bench' },
  { out: 'ammo762', n: 15, cost: { metal: 3, gunpowder: 2 }, st: 'bench' },
  { out: 'bolt', n: 6, cost: { wood: 2, metal: 1 } },
  { out: 'knife', n: 1, cost: { metal: 2, cloth: 1 } },
  { out: 'machete', n: 1, cost: { metal: 5, cloth: 1 }, st: 'bench' },
  { out: 'bat', n: 1, cost: { wood: 4, metal: 1 } },
  { out: 'axe', n: 1, cost: { wood: 3, metal: 2 } },
  { out: 'pickaxe', n: 1, cost: { wood: 3, metal: 3 } },
  { out: 'crowbar', n: 1, cost: { metal: 5 }, st: 'bench' },
  { out: 'wrench', n: 1, cost: { metal: 3 }, st: 'bench' },
  { out: 'sledge', n: 1, cost: { metal: 10, wood: 4 }, st: 'bench' },
  { out: 'chainsaw', n: 1, cost: { metal: 14, parts: 10, electro: 2 }, st: 'bench' },
  { out: 'crossbow', n: 1, cost: { wood: 6, rope: 2, parts: 3 }, st: 'bench' },
  { out: 'pistol', n: 1, cost: { metal: 8, parts: 5 }, st: 'bench' },
  { out: 'revolver', n: 1, cost: { metal: 10, parts: 6 }, st: 'bench' },
  { out: 'sawnoff', n: 1, cost: { metal: 9, parts: 5, wood: 3 }, st: 'bench' },
  { out: 'shotgun', n: 1, cost: { metal: 12, parts: 7, wood: 4 }, st: 'bench' },
  { out: 'smg', n: 1, cost: { metal: 14, parts: 10 }, st: 'bench' },
  { out: 'rifle', n: 1, cost: { metal: 12, parts: 8, wood: 6 }, st: 'bench' },
  { out: 'ak', n: 1, cost: { metal: 18, parts: 12 }, st: 'bench' },
  { out: 'flamer', n: 1, cost: { metal: 20, parts: 12, fuel: 2 }, st: 'bench' },
  { out: 'bow', n: 1, cost: { wood: 5, rope: 2 } },
  { out: 'arrow', n: 8, cost: { wood: 2, stone: 1 } },
  { out: 'spear', n: 1, cost: { wood: 3, metal: 2, rope: 1 } },
  { out: 'torch_h', n: 1, cost: { wood: 1, cloth: 1 } },
  { out: 'shovel', n: 1, cost: { wood: 2, metal: 3 }, st: 'bench' },
  { out: 'fireaxe', n: 1, cost: { metal: 6, wood: 3, parts: 1 }, st: 'bench' },
  { out: 'nailgun', n: 1, cost: { metal: 8, parts: 6, electro: 2, battery: 1 }, st: 'bench' },
  { out: 'nails', n: 30, cost: { metal: 1 }, st: 'bench' },
  { out: 'detector', n: 1, cost: { electro: 4, parts: 4, metal: 2, battery: 1 }, st: 'bench' },
  { out: 'walkie', n: 1, cost: { electro: 3, parts: 2, battery: 1 }, st: 'bench' },
  { out: 'gl_shell', n: 2, cost: { metal: 2, gunpowder: 4, parts: 1 }, st: 'bench' },
  { out: 'glauncher', n: 1, cost: { metal: 24, parts: 16, electro: 3 }, st: 'bench' },
  { out: 'pipe', n: 2, cost: { metal: 3 }, st: 'bench' },
  { out: 'brick', n: 4, cost: { stone: 4, wood: 1 }, st: 'fire' },
  { out: 'flashlight', n: 1, cost: { metal: 1, electro: 1 } },
  { out: 'rod', n: 1, cost: { wood: 2, rope: 1 } },
  { out: 'hammer', n: 1, cost: { wood: 2, metal: 2 } },
  { out: 'leash', n: 1, cost: { leather: 1, rope: 1 } },
  { out: 'fish_cooked', n: 1, cost: { fish: 1 }, st: 'fire' },
  { out: 'decoy', n: 2, cost: { electro: 1, parts: 1, metal: 1 }, st: 'bench' },
  { out: 'flare', n: 2, cost: { gunpowder: 1, cloth: 1 }, st: 'bench' },
  { out: 'flaregun', n: 1, cost: { metal: 6, parts: 3 }, st: 'bench' },
  { out: 'nvg', n: 1, cost: { electro: 5, parts: 4, metal: 2, battery: 1 }, st: 'bench' },
  { out: 'leather', n: 2, cost: { junk_boot: 1 }, st: 'bench' },
  { out: 'repairkit', n: 1, cost: { metal: 4, parts: 3 }, st: 'bench' },
  { out: 'engine', n: 1, cost: { metal: 15, parts: 12, electro: 2 }, st: 'garage' },
  { out: 'wheel', n: 1, cost: { metal: 3, leather: 2 }, st: 'garage' },
  { out: 'beanie', n: 1, cost: { cloth: 3 } },
  { out: 'ushanka', n: 1, cost: { fur: 3, cloth: 2 } },
  { out: 'parka', n: 1, cost: { fur: 5, cloth: 6, leather: 2 }, st: 'bench' },
  { out: 'jacket', n: 1, cost: { cloth: 6, leather: 1 } },
  { out: 'vest', n: 1, cost: { metal: 12, cloth: 6 }, st: 'bench' },
  { out: 'bp_small', n: 1, cost: { cloth: 6, rope: 2 } },
  { out: 'bp_big', n: 1, cost: { cloth: 8, leather: 4, rope: 3 }, st: 'bench' },
];
TZ.VEHICLE_RECIPES = [
  { out: 'boat', st: null, name: 'Деревянная лодка', cost: { wood: 30, rope: 4, cloth: 4 }, desc: 'Собирается руками у воды (до 10 клеток). Вёсла — без топлива. Катер с мотором можно только найти.' },
  { out: 'gyro', name: 'Самодельный вертолёт', cost: { pipe: 40, metal: 30, engine: 1, parts: 30, electro: 8, cloth: 10, battery: 1 }, desc: 'Автожир из труб на одного. Взлетает на месте: Shift — вверх, Пробел — вниз. Очень дорогой.' },
  { out: 'ultralight', name: 'Самодельный самолёт', cost: { pipe: 36, cloth: 24, metal: 24, engine: 1, parts: 24, rope: 8, electro: 6 }, desc: 'Дельталёт из труб и ткани. Нужен разбег по ровному месту. Очень дорогой.' },
  { out: 'buggy', name: 'Самодельный багги', cost: { metal: 60, parts: 30, engine: 1, wheel: 4, battery: 1, electro: 4 }, desc: 'Быстрый внедорожник из металлолома. Только его можно прокачивать в гараже: таран, шипы, броня, турбо.' },
];

// ---------------------------------------------------------------- BUGGY UPGRADES (garage, expensive on purpose)
TZ.VEHICLE_MODS = {
  engine1: { name: 'Форсированный двигатель', cost: { engine: 1, parts: 25, metal: 20, electro: 6 }, desc: '+16% к скорости, +25% к разгону' },
  engine2: { name: 'Турбо-двигатель', cost: { engine: 1, parts: 40, metal: 30, electro: 12, fuel: 5 }, req: 'engine1', desc: 'Ещё +16% скорости и +25% разгона. Рёв слышно за километр.' },
  ram: { name: 'Таран', cost: { metal: 55, parts: 12, concrete: 6 }, desc: 'Удар по зомби в 1.7 раза сильнее, машина почти не теряет скорость и прочность при столкновениях' },
  spikes: { name: 'Шипы', cost: { metal: 40, parts: 10, gunpowder: 4 }, desc: 'Зомби, вцепившиеся в борта, получают урон и замедляются' },
  armor: { name: 'Бронелисты', cost: { metal: 80, parts: 16, concrete: 10 }, desc: '+70% прочности, когти зомби почти не царапают. Машина чуть тяжелее и медленнее' },
  tank: { name: 'Двойной бак', cost: { metal: 25, parts: 10, fuel: 4 }, desc: 'Запас топлива в 2 раза больше' },
  tires: { name: 'Внедорожные шины', cost: { wheel: 4, leather: 10, parts: 8 }, desc: 'По песку, снегу и бездорожью — почти как по асфальту' },
  light: { name: 'Люстра прожекторов', cost: { electro: 10, parts: 8, metal: 8, battery: 1 }, desc: 'Фары светят намного дальше' },
};

// ---------------------------------------------------------------- ZOMBIES
TZ.ZOMBIES = {
  walker:   { name: 'Ходячий', hp: 65, speed: 1.0, dmg: 9, cd: 1.1, wall: 9, r: 0.3, scale: 1, score: 10 },
  runner:   { name: 'Бегун', hp: 42, speed: 2.25, dmg: 7, cd: 0.75, wall: 5, r: 0.28, scale: 0.95, score: 15 },
  crawler:  { name: 'Ползун', hp: 35, speed: 0.65, dmg: 8, cd: 1.0, wall: 4, r: 0.3, scale: 1, score: 8, crawl: 1 },
  spitter:  { name: 'Плевун', hp: 80, speed: 0.9, dmg: 8, cd: 1.2, wall: 6, r: 0.33, scale: 1.05, score: 25, ranged: { range: 6.5, cd: 3.2, dmg: 13 } },
  exploder: { name: 'Взрывун', hp: 70, speed: 1.15, dmg: 0, cd: 1.0, wall: 0, r: 0.34, scale: 1.05, score: 25, explode: { r: 2.6, dmg: 45 } },
  screamer: { name: 'Крикун', hp: 55, speed: 1.3, dmg: 6, cd: 1.0, wall: 4, r: 0.28, scale: 0.95, score: 30, scream: 1 },
  soldier:  { name: 'Солдат', hp: 140, speed: 1.0, dmg: 12, cd: 1.1, wall: 12, r: 0.32, scale: 1, score: 35, armor: 0.5 },
  frozen:   { name: 'Ледяной', hp: 120, speed: 0.8, dmg: 14, cd: 1.3, wall: 12, r: 0.32, scale: 1.05, score: 30, chill: 1 },
  husk:     { name: 'Высохший', hp: 58, speed: 1.55, dmg: 10, cd: 0.9, wall: 6, r: 0.28, scale: 0.98, score: 20, dry: 1 },
  brute:    { name: 'Громила', hp: 420, speed: 0.72, dmg: 28, cd: 1.5, wall: 55, r: 0.48, scale: 1.45, score: 60 },
  boss:     { name: 'Бегемот', hp: 3200, speed: 0.85, dmg: 45, cd: 1.6, wall: 180, r: 0.85, scale: 2.1, score: 500, boss: 1 },
};
TZ.ANIMALS = {
  deer: { name: 'Олень', hp: 60, speed: 3.6, dmg: 0, flee: 1, r: 0.4, drops: { raw_meat: [2, 3], leather: [1, 2] } },
  wolf: { name: 'Волк', hp: 70, speed: 3.3, dmg: 10, cd: 0.9, r: 0.35, pack: 1, drops: { raw_meat: [1, 2], fur: [1, 2] } },
  dog:  { name: 'Собака', hp: 150, speed: 3.6, dmg: 16, cd: 0.75, r: 0.3, dog: 1, drops: { raw_meat: [1, 1] } },
  bear: { name: 'Медведь', hp: 480, speed: 2.6, dmg: 32, cd: 1.4, r: 0.6, drops: { raw_meat: [4, 6], fur: [3, 4], leather: [2, 3] } },
};

// ---------------------------------------------------------------- VEHICLES
TZ.VEHICLES = {
  sedan:  { name: 'Седан', hp: 100, speed: 11, accel: 6, turn: 2.2, fuel: 60, seats: 4, off: 0.6, snow: 0.45, mass: 1, len: 2.6, wid: 1.2 },
  hatch:  { name: 'Хэтчбек', hp: 90, speed: 10, accel: 6.5, turn: 2.5, fuel: 50, seats: 4, off: 0.6, snow: 0.45, mass: 0.9, len: 2.3, wid: 1.15 },
  pickup: { name: 'Пикап', hp: 140, speed: 10, accel: 5, turn: 2.0, fuel: 80, seats: 2, off: 0.8, snow: 0.6, mass: 1.4, len: 3.0, wid: 1.3 },
  police: { name: 'Полицейская машина', hp: 120, speed: 12.5, accel: 7, turn: 2.3, fuel: 60, seats: 4, off: 0.6, snow: 0.45, mass: 1.1, len: 2.6, wid: 1.2 },
  uaz:    { name: 'УАЗ', hp: 170, speed: 9.5, accel: 5, turn: 2.1, fuel: 80, seats: 4, off: 0.95, snow: 0.8, mass: 1.5, len: 2.6, wid: 1.3 },
  buggy:  { name: 'Багги', hp: 110, speed: 12, accel: 8, turn: 2.8, fuel: 40, seats: 2, off: 1.0, snow: 0.75, mass: 0.8, len: 2.1, wid: 1.3 },
  boat:   { name: 'Лодка', hp: 60, speed: 4.6, accel: 3, turn: 1.9, fuel: 0, nofuel: 1, seats: 2, off: 1, snow: 1, mass: 0.6, len: 2.2, wid: 1.0, water: 1 },
  motorboat: { name: 'Катер', hp: 130, speed: 13.5, accel: 6, turn: 1.9, fuel: 70, seats: 4, off: 1, snow: 1, mass: 1.2, len: 3.2, wid: 1.4, water: 1 },
  heli:   { name: 'Вертолёт Ми-2', hp: 240, speed: 18, accel: 6, turn: 2.0, fuel: 140, seats: 4, off: 0.4, snow: 0.4, mass: 2.2, len: 3.4, wid: 1.4, air: 'heli' },
  plane:  { name: 'Самолёт Ан-2', hp: 210, speed: 21, accel: 4.2, turn: 1.15, fuel: 160, seats: 4, off: 0.55, snow: 0.45, mass: 2.4, len: 4.0, wid: 1.4, air: 'plane', takeoff: 9 },
  gyro:   { name: 'Самодельный вертолёт', hp: 90, speed: 13, accel: 5, turn: 2.3, fuel: 50, seats: 1, off: 0.4, snow: 0.4, mass: 0.9, len: 2.4, wid: 1.0, air: 'heli' },
  ultralight: { name: 'Самодельный самолёт', hp: 80, speed: 15, accel: 3.8, turn: 1.5, fuel: 50, seats: 1, off: 0.6, snow: 0.45, mass: 0.8, len: 2.4, wid: 1.0, air: 'plane', takeoff: 7 },
  snowmobile: { name: 'Снегоход', hp: 70, speed: 11, accel: 7, turn: 2.8, fuel: 35, seats: 2, off: 0.7, snow: 1.15, mass: 0.6, len: 1.9, wid: 0.8 },
};

// ---------------------------------------------------------------- BIOMES
TZ.BIOMES = [
  { id: 'forest', name: 'Осенний лес', cold: 0, fog: 0 },
  { id: 'plains', name: 'Поля', cold: 0, fog: 0 },
  { id: 'snow', name: 'Заснеженная тайга', cold: 1, fog: 0 },
  { id: 'swamp', name: 'Болото', cold: 0, fog: 1, toxic: 1 },
  { id: 'waste', name: 'Пустошь', cold: 0, fog: 0, hot: 1 },
  { id: 'desert', name: 'Пустыня', cold: 0, fog: 0, hot: 2, dry: 1 },
];

// ---------------------------------------------------------------- LOOT
TZ.LOOT = {
  cabinet:  [['canned', .3, 1, 2], ['beans', .25, 1, 2], ['water', .35, 1, 2], ['bandage', .3, 1, 2], ['cloth', .45, 1, 3], ['parts', .2, 1, 2], ['ammo9', .14, 4, 10], ['antibio', .08, 1, 1], ['painkill', .08, 1, 1], ['energy', .1, 1, 1], ['knife', .03, 1, 1], ['coffee', .1, 1, 1], ['vodka', .06, 1, 1], ['electro', .1, 1, 1], ['beanie', .03, 1, 1], ['jacket', .03, 1, 1]],
  fridge:   [['canned', .4, 1, 3], ['water', .55, 1, 3], ['veggie', .3, 1, 2], ['soda', .35, 1, 2], ['energy', .15, 1, 1], ['raw_meat', .15, 1, 2], ['apple', .2, 1, 3]],
  crate:    [['wood', .6, 2, 4], ['metal', .45, 1, 3], ['cloth', .3, 1, 2], ['parts', .3, 1, 2], ['rope', .2, 1, 2], ['ammo9', .1, 4, 8], ['canned', .15, 1, 1], ['gunpowder', .1, 1, 3]],
  car:      [['metal', .7, 1, 3], ['parts', .45, 1, 2], ['fuel', .3, 1, 1], ['cloth', .25, 1, 2], ['water', .15, 1, 1], ['ammo9', .08, 3, 8], ['chips', .2, 1, 2], ['electro', .2, 1, 1], ['repairkit', .05, 1, 1], ['wrench', .04, 1, 1]],
  police:   [['walkie', .15, 1, 1], ['flaregun', .06, 1, 1], ['flare', .2, 1, 3], ['ammo9', .8, 8, 16], ['ammo357', .3, 4, 8], ['ammo12', .35, 3, 6], ['bandage', .35, 1, 2], ['pistol', .15, 1, 1], ['revolver', .06, 1, 1], ['shotgun', .06, 1, 1], ['vest', .06, 1, 1], ['painkill', .2, 1, 1]],
  military: [['pipe', .2, 2, 4], ['pkm', .015, 1, 1], ['glauncher', .02, 1, 1], ['gl_shell', .15, 1, 3], ['walkie', .12, 1, 1], ['nvg', .05, 1, 1], ['flare', .3, 2, 4], ['flaregun', .08, 1, 1], ['ammo762', .7, 10, 25], ['ammo9', .4, 8, 16], ['ammo12', .3, 4, 8], ['medkit', .3, 1, 1], ['molotov', .2, 1, 2], ['grenade', .25, 1, 2], ['mre', .4, 1, 2], ['ak', .07, 1, 1], ['rifle', .05, 1, 1], ['svd', .02, 1, 1], ['helmet', .1, 1, 1], ['vest', .06, 1, 1], ['bp_mil', .05, 1, 1], ['gasmask', .08, 1, 1], ['adrenaline', .1, 1, 1], ['gunpowder', .3, 2, 4]],
  trash:    [['pipe', .12, 1, 2], ['cloth', .5, 1, 2], ['metal', .45, 1, 2], ['parts', .25, 1, 1], ['canned', .1, 1, 1], ['wood', .3, 1, 2], ['dirty_water', .2, 1, 1], ['chips', .15, 1, 1], ['electro', .08, 1, 1]],
  shop:     [['walkie', .04, 1, 1], ['detector', .03, 1, 1], ['torch_h', .05, 1, 1], ['rod', .08, 1, 1], ['leash', .06, 1, 1], ['canned', .5, 1, 3], ['beans', .4, 1, 3], ['water', .6, 1, 3], ['soda', .4, 1, 2], ['chips', .5, 1, 3], ['choco', .4, 1, 2], ['energy', .3, 1, 2], ['fuel', .3, 1, 1], ['cloth', .3, 1, 2], ['bandage', .25, 1, 2], ['coffee', .2, 1, 2], ['vodka', .15, 1, 1]],
  locker:   [['fireaxe', .04, 1, 1], ['walkie', .05, 1, 1], ['ammo9', .45, 6, 14], ['bandage', .4, 1, 2], ['antibio', .2, 1, 1], ['medkit', .12, 1, 1], ['bat', .06, 1, 1], ['flashlight', .1, 1, 1], ['bp_small', .06, 1, 1], ['crowbar', .05, 1, 1], ['jacket', .06, 1, 1]],
  medical:  [['bandage', .7, 2, 4], ['medkit', .45, 1, 2], ['antibio', .5, 1, 2], ['painkill', .4, 1, 2], ['adrenaline', .15, 1, 1], ['cloth', .4, 1, 3]],
  garage:   [['pipe', .35, 2, 6], ['nailgun', .06, 1, 1], ['nails', .3, 10, 30], ['fireaxe', .05, 1, 1], ['shovel', .15, 1, 1], ['hammer', .2, 1, 1], ['wrench', .2, 1, 1], ['repairkit', .35, 1, 1], ['wheel', .3, 1, 1], ['battery', .25, 1, 1], ['fuel', .5, 1, 2], ['parts', .6, 2, 4], ['metal', .6, 2, 5], ['electro', .25, 1, 2], ['sledge', .04, 1, 1], ['chainsaw', .03, 1, 1]],
  cabin:    [['bow', .06, 1, 1], ['arrow', .2, 4, 10], ['spear', .05, 1, 1], ['shovel', .1, 1, 1], ['torch_h', .12, 1, 1], ['rod', .2, 1, 1], ['hammer', .12, 1, 1], ['leash', .1, 1, 1], ['canned', .3, 1, 2], ['fur', .3, 1, 2], ['ushanka', .1, 1, 1], ['parka', .06, 1, 1], ['rifle', .05, 1, 1], ['ammo762', .25, 5, 10], ['vodka', .3, 1, 2], ['coffee', .2, 1, 1], ['rope', .3, 1, 2], ['crossbow', .04, 1, 1], ['bolt', .2, 4, 8]],
  lab:      [['decoy', .3, 1, 2], ['nvg', .06, 1, 1], ['electro', .7, 2, 5], ['antibio', .5, 1, 2], ['medkit', .3, 1, 1], ['gasmask', .25, 1, 1], ['adrenaline', .25, 1, 1], ['parts', .5, 2, 4], ['battery', .15, 1, 1], ['katana', .02, 1, 1]],
  drop:     [['pkm', .05, 1, 1], ['glauncher', .06, 1, 1], ['gl_shell', .4, 2, 4], ['detector', .15, 1, 1], ['walkie', .3, 1, 1], ['flare', .6, 2, 4], ['nvg', .12, 1, 1], ['decoy', .4, 1, 2], ['medkit', 1, 1, 2], ['ammo9', 1, 15, 30], ['ammo762', .7, 15, 30], ['ammo12', .6, 6, 12], ['mre', 1, 2, 3], ['water', 1, 2, 4], ['parts', 1, 3, 6], ['antibio', .5, 1, 2], ['grenade', .5, 1, 3], ['ak', .15, 1, 1], ['shotgun', .2, 1, 1], ['svd', .06, 1, 1], ['vest', .15, 1, 1], ['repairkit', .4, 1, 2], ['electro', .6, 2, 4]],
  cache:    [['ammo9', .6, 10, 25], ['ammo762', .45, 10, 25], ['ammo12', .4, 4, 10], ['gl_shell', .1, 1, 2], ['canned', .6, 2, 4], ['water', .5, 1, 3], ['medkit', .35, 1, 1], ['antibio', .3, 1, 2], ['gunpowder', .4, 2, 5], ['parts', .5, 2, 5], ['electro', .3, 1, 3], ['grenade', .2, 1, 2], ['vodka', .3, 1, 2], ['revolver', .08, 1, 1], ['smg', .06, 1, 1], ['ak', .04, 1, 1], ['battery', .15, 1, 1], ['nvg', .03, 1, 1]],
  bush:     [['berries', 0.85, 1, 3]],
  appletree:[['apple', 0.9, 2, 4]],
};

TZ.DIFFICULTY = {
  easy:   { name: 'Лёгкая', zhp: 0.8, zdmg: 0.6, horde: 0.7, drain: 0.7, rn: 0.5 },
  normal: { name: 'Нормальная', zhp: 1, zdmg: 1, horde: 1, drain: 1, rn: 1 },
  hard:   { name: 'Кошмар', zhp: 1.3, zdmg: 1.5, horde: 1.5, drain: 1.25, rn: 1.6 },
};

// ---------------------------------------------------------------- SURVIVOR NAMES
TZ.SURV_NAMES_M = ['Степан', 'Лёха', 'Борис', 'Котов', 'Гена', 'Витёк', 'Михалыч', 'Артём', 'Денис', 'Саня', 'Игорь', 'Фёдор', 'Рустам', 'Паша', 'Олег', 'Тимур', 'Егор', 'Гоша'];
TZ.SURV_NAMES_F = ['Марина', 'Ника', 'Ася', 'Оля', 'Катя', 'Вера', 'Лиза', 'Таня', 'Даша', 'Зоя', 'Алёна', 'Юля'];
TZ.ROLES = {
  medic:    { name: 'Медик', desc: 'Лечит вас и команду рядом.' },
  gatherer: { name: 'Добытчик', desc: 'Каждое утро приносит ресурсы.' },
  mechanic: { name: 'Механик', desc: 'Чинит стены, турели и машины рядом.' },
  shooter:  { name: 'Стрелок', desc: 'Точный огонь, повышенный урон.' },
  cook:     { name: 'Повар', desc: 'Каждое утро готовит еду из запасов.' },
};
